print ("Hola mundo")
print("Hola Rapha querido!")
print ("Como va todo Juanma?")
print("Muy bien, con hambre ya. Que cenas hoy?")
print ("Y la champions empieza ya, hoy pollito con zuccini, vos que?")