print ("Hola mundo")
print("Hola Rapha querido!")
print ("Como va todo Juanma?")
print("Muy bien, con hambre ya. Que cenas hoy?")
print ("Y la champions empieza ya, hoy pollito con zuccini, vos que?")
print("uff cierto, Vamo Arsenal, anti PSG siempre. Ni idea jaja rezandole a mi pareja :D")
